provider: terraform-module
template: parameterized-go
providerDefaultBranch: main
noSchema: true
major-version: 0
test-folder: tests
shards: 8
aws: true
freeDiskSpaceBeforeBuild: true
freeDiskSpaceBeforeTest: true
modulePath: .
esc:
  enabled: true
  environment: imports/github-secrets # No repo-specific secrets.
env:
  AWS_REGION: "us-west-2"
