provider: terraform-module
template: parameterized-go
noSchema: true
major-version: 0
test-folder: tests
shards: 2
aws: true
modulePath: .
env:
  AWS_REGION: "us-west-2"

actions:
  preTest:
    - name: Install opentofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_wrapper: false
  preBuild:
    - name: Install opentofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_wrapper: false
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ env.AWS_REGION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-duration-seconds: 7200
        role-session-name: terraform-module@githubActions
        role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
