# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .vpc import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "terraform-aws-modules",
  "mod": "index",
  "fqn": "pulumi_terraform_aws_modules",
  "classes": {
   "terraform-aws-modules:index:Vpc": "Vpc"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "terraform-aws-modules",
  "token": "pulumi:providers:terraform-aws-modules",
  "fqn": "pulumi_terraform_aws_modules",
  "class": "Provider"
 }
]
"""
)
