// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vpc;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * provider configuration for aws
     * 
     */
    @Import(name="aws", json=true)
    private @Nullable Output<Map<String,Object>> aws;

    /**
     * @return provider configuration for aws
     * 
     */
    public Optional<Output<Map<String,Object>>> aws() {
        return Optional.ofNullable(this.aws);
    }

    /**
     * Set to true to use OpenTofu to run the module.
     * 
     */
    @Import(name="useOpentofu", json=true)
    private @Nullable Output<Boolean> useOpentofu;

    /**
     * @return Set to true to use OpenTofu to run the module.
     * 
     */
    public Optional<Output<Boolean>> useOpentofu() {
        return Optional.ofNullable(this.useOpentofu);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.aws = $.aws;
        this.useOpentofu = $.useOpentofu;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param aws provider configuration for aws
         * 
         * @return builder
         * 
         */
        public Builder aws(@Nullable Output<Map<String,Object>> aws) {
            $.aws = aws;
            return this;
        }

        /**
         * @param aws provider configuration for aws
         * 
         * @return builder
         * 
         */
        public Builder aws(Map<String,Object> aws) {
            return aws(Output.of(aws));
        }

        /**
         * @param useOpentofu Set to true to use OpenTofu to run the module.
         * 
         * @return builder
         * 
         */
        public Builder useOpentofu(@Nullable Output<Boolean> useOpentofu) {
            $.useOpentofu = useOpentofu;
            return this;
        }

        /**
         * @param useOpentofu Set to true to use OpenTofu to run the module.
         * 
         * @return builder
         * 
         */
        public Builder useOpentofu(Boolean useOpentofu) {
            return useOpentofu(Output.of(useOpentofu));
        }

        public ProviderArgs build() {
            $.useOpentofu = Codegen.booleanProp("useOpentofu").output().arg($.useOpentofu).env("PULUMI_TERRAFORM_MODULE_USE_OPENTOFU").def(false).getNullable();
            return $;
        }
    }

}
