// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vpc.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FlowLogCloudwatchIamRoleConditionsArgs extends com.pulumi.resources.ResourceArgs {

    public static final FlowLogCloudwatchIamRoleConditionsArgs Empty = new FlowLogCloudwatchIamRoleConditionsArgs();

    @Import(name="test")
    private @Nullable Output<String> test;

    public Optional<Output<String>> test() {
        return Optional.ofNullable(this.test);
    }

    @Import(name="values")
    private @Nullable Output<List<String>> values;

    public Optional<Output<List<String>>> values() {
        return Optional.ofNullable(this.values);
    }

    @Import(name="variable")
    private @Nullable Output<String> variable;

    public Optional<Output<String>> variable() {
        return Optional.ofNullable(this.variable);
    }

    private FlowLogCloudwatchIamRoleConditionsArgs() {}

    private FlowLogCloudwatchIamRoleConditionsArgs(FlowLogCloudwatchIamRoleConditionsArgs $) {
        this.test = $.test;
        this.values = $.values;
        this.variable = $.variable;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FlowLogCloudwatchIamRoleConditionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FlowLogCloudwatchIamRoleConditionsArgs $;

        public Builder() {
            $ = new FlowLogCloudwatchIamRoleConditionsArgs();
        }

        public Builder(FlowLogCloudwatchIamRoleConditionsArgs defaults) {
            $ = new FlowLogCloudwatchIamRoleConditionsArgs(Objects.requireNonNull(defaults));
        }

        public Builder test(@Nullable Output<String> test) {
            $.test = test;
            return this;
        }

        public Builder test(String test) {
            return test(Output.of(test));
        }

        public Builder values(@Nullable Output<List<String>> values) {
            $.values = values;
            return this;
        }

        public Builder values(List<String> values) {
            return values(Output.of(values));
        }

        public Builder values(String... values) {
            return values(List.of(values));
        }

        public Builder variable(@Nullable Output<String> variable) {
            $.variable = variable;
            return this;
        }

        public Builder variable(String variable) {
            return variable(Output.of(variable));
        }

        public FlowLogCloudwatchIamRoleConditionsArgs build() {
            return $;
        }
    }

}
