name: on-pr

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_REGION: us-west-2

on:
  - pull_request

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 7200
          role-session-name: pulumi-terraform-module-provider@githubActions
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: |
            go.sum
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Check worktree clean
        id: worktreeClean
        uses: pulumi/git-status-check-action@v1
        with:
          # Keep these in sync with the Renovate step below to avoid them getting checked in.
          # TODO[pulumi/pulumi-terraform-module-provider#79] unwanted file generated
          allowed-changes: |
            **/pulumi-plugin.json
            **/*.csproj
            **/pulumiUtilities.go
            **/package.json
            **/pyproject.toml
            **/schema-terraform-module-provider.json
            **/pom.xml
